# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: '/WRDR-My-Diary'
baseurl_posts_img: '/WRDR-My-Diary/assets/images/posts/'
baseurl_featured_img: '/WRDR-My-Diary/assets/images/hero/'
baseurl_featured_thumbnail: '/WRDR-My-Diary/assets/images/thumbnail/'
baseurl_javascripts: '/WRDR-My-Diary/assets/javascripts/'

# ç½‘é¡µçš„æ ‡é¢˜
title: "æ£’çƒå°‘å¥³å¾å°”è¾¾å°”"
# ç½‘ç«™çš„ä¸»æ ‡é¢˜
name: "âš¾ï¸æ£’çƒå°‘å¥³å¾å°”è¾¾å°”"
description: "ğŸŒŸhi~ä½ å¥½ï¼Œæˆ‘æ˜¯å¾å°”è¾¾å°”ï¼Œå¾ˆé«˜å…´è®¤è¯†ä½ ã€‚"

url: site url
icon: your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus: disqus_shortname # get it on https://disqus.com/admin/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
permalink: /:title/

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: [ changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock ]
